version: '3'
services:
  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    env_file: .env
    ports:
      - "${PORT_NGINX}:80"
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime
      - "./:/opt/app"
    command: nginx
    
    
  php-fpm:
    container_name: ${APP_NAME}-php
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime
      - "./:/opt/app"
    stdin_open: true
    tty: true
    command: php-fpm